### ISSUE TITLE
Possibility to connect to CrashLoopbackOff pod

### ISSUE THREAD

**Issue by andreyradygin** [aylei/kubectl-debug#8]
Hi there!  
It's FR. It would be just great, to have possibility to connect and debug crashing pods (I meant CrashLoopbackOff). So we see "bad" pod, and there are no meaningful logs in the pod describe and we could connect into it and do some useful things.  
What do you think about such feature? Could such thing be done?

**Comment by aylei** [comment]
This feature can be really useful but cannot be implemented "directly" IMHO, because the problematic container in the crashing pod is re-created constantly, there is no consistent pid namespace to diagnose the container process.
A possible workaround is 'fork' a new pod, overwrite the container entrypoint to something like 'bash', and diagnose the new pod, which is adopted by the [`oc debug`](https://www.mankier.com/1/oc-debug) command. I planned to add the same feature in #1

**Comment by andreioss** [comment]
Oh sorry, you're right, I should read old issues more carefully.
I was thinking about this problem and come to the same conclusion.
BUT, we need fork bad pod/container with some "bash" command AND possibility to attach to it with debug image at the same time.

Btw, I have a lot of opportunities to test your utility if you interesting.

**Comment by aylei** [comment]
Sure! I will implement a working prototype this days, hope that fits your case.

**Comment by aylei** [comment]
@andreioss 
I've add the basic support in #11 , would you like to try it our and give me some feedback?

Note: when you enter the debug container, the filesystem of forked container is located in `/proc/$pid/root`. If you want to run the binary in forked container, run `chroot /proc/$pid/root sh` first.

**Comment by aylei** [comment]
Just fetch the `issue-1` branch, or I will release a preview binary this night😄

**Comment by andreioss** [comment]
If you'll provide the binary, it would be great, thanks :)

**Comment by aylei** [comment]
https://github.com/aylei/kubectl-debug/releases/tag/0.0.2-pre

Tested locally and seems fine for me, looking forward your advice!

**Comment by aylei** [comment]
@andreyradygin 
I've merged this feature and you may access it in the pre-release before the 0.2.0 release comes out.
