### ISSUE TITLE
kubectl debug never connects

### ISSUE THREAD

**Issue by dmayle** [aylei/kubectl-debug#88]
From the client:
```
Agent Pod info: [Name:debug-agent-pod-c632639e-200e-11ea-bb14-024283a9b9b2, Namespace:default, Image:aylei/debug-agent:latest, HostPort:10027, ContainerPort:10027]
Waiting for pod debug-agent-pod-c632639e-200e-11ea-bb14-024283a9b9b2 to run...
pod hellopy-5db6788688-kd5xz PodIP 10.244.10.93, agentPodIP 192.168.19.103
wait for forward port to debug agent ready...
Forwarding from 127.0.0.1:10027 -> 10027
Forwarding from [::1]:10027 -> 10027
Handling connection for 10027
```

From the debug agent:
```
2019/12/16 14:17:26 Listening on 0.0.0.0:10027 
2019/12/16 14:17:28 receive debug request
2019/12/16 14:17:28 http: superfluous response.WriteHeader call from k8s.io/apimachinery/pkg/util/httpstream/spdy.responseUpgrader.UpgradeResponse (upgrade.go:91)
```

**Comment by dee0** [comment]
Just started trying to use kubectl-debug myself and ran into this.    Does anyone know of a work around?

**Comment by dee0** [comment]
Couple of things
- Believe dmayle left out this message
  E0403 22:33:34.210311    4348 httpstream.go:188] timed out waiting for client to create streams

- Been trying to println debug this.   I see the client calls Negotiate in spdy.go and that executes as far as the call to upgrader.NewConnection.    However that never returns.

**Comment by dee0** [comment]
I think what is happening is 
- In the plugin, there is an attempt to get a container id from the specified pod.
  ( cmd.go Run, between lines 429 and 475 )   This is coming up with a value like 
  containerd://68620696047ddb08fa2ea8042aadc75d36764ef35bb551252176f02596c00537]
- In the agent, in server.go around line 76 in the function ServeDebug there is a check to see if the container id begins with docker://.   Because it does not, the agent calls http.Error.    This causes headers to be sent.
   However ServeDebug doesn't abort.    It keeps executing
- Back in the plugin, it is going to hang because it will try to upgrade the connection but the connection is in a bad state.
- In the agent it will also try to proceed to the point where it upgrades the connection.   This cases a second call to send headers.   The functoin WriterHeader in server.go detects this and reports the 'superflous call' and aborts.   Later the code waiting for the streams to be established times out.

Not sure if the check for docker:// can just be removed and/or how to work around this.

**Comment by dee0** [comment]
I tried removing the check for docker://.   Things progressed further but still did not work in the end.

> Handling connection for 10027
                             2020/04/04 06:14:06 spdy Negotiate Making NewConnection
2020/04/04 06:14:06 remotecommand Stream negotiationed &{conn:0xc0007d80b0 streams:[] streamLock:{state:0 sema:0} newStreamHandler:0x716c50} v4.channel.k8s.io
                                                                                                                                                              set container procfs correct false .. 
pulling image nicolaka/netshoot:latest... 
end port-forward...
error execute remote, Internal error occurred: error attaching to container: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
error: Internal error occurred: error attaching to container: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Is there a prerequisite that docker be on the system and running?

**Comment by markzhang0928** [comment]
> From the client:
> 
> ```
> Agent Pod info: [Name:debug-agent-pod-c632639e-200e-11ea-bb14-024283a9b9b2, Namespace:default, Image:aylei/debug-agent:latest, HostPort:10027, ContainerPort:10027]
> Waiting for pod debug-agent-pod-c632639e-200e-11ea-bb14-024283a9b9b2 to run...
> pod hellopy-5db6788688-kd5xz PodIP 10.244.10.93, agentPodIP 192.168.19.103
> wait for forward port to debug agent ready...
> Forwarding from 127.0.0.1:10027 -> 10027
> Forwarding from [::1]:10027 -> 10027
> Handling connection for 10027
> ```
> 
> From the debug agent:
> 
> ```
> 2019/12/16 14:17:26 Listening on 0.0.0.0:10027 
> 2019/12/16 14:17:28 receive debug request
> 2019/12/16 14:17:28 http: superfluous response.WriteHeader call from k8s.io/apimachinery/pkg/util/httpstream/spdy.responseUpgrader.UpgradeResponse (upgrade.go:91)
> ```

I think the problem might be caused by the remote kube-apiserver couldn't  response kubeletremote.ServeAttach() request correctly? could you please check your kubelet status of your target container host?

**Comment by dee0** [comment]
Thanks for the input.   The kubelet seems fine.    After digging into this more I think I see what is going on.   The container runtime used in my environment is 'remote' as opposed to 'docker'.  ( See this in the command line args passed to kubelet. )
However at least at the moment kubectl-debug seems to only work with kubelets where the docker runtime is in use.   I can say this because I see that the code 
- assumes the containers in the target pod will have ids of the form docker://
   ( In my case they actually have the form containerd:// )
- assumes that it can create the debug container using a docker client the end point unix:///var/run/docker.sock.  ( In my case nothing is listening on that socket )

**Comment by aylei** [comment]
@dee0 Yes, docker is the only supported runtime right now.😔

> assumes the containers in the target pod will have ids of the form docker:// ( In my case they actually have the form containerd:// )

The agent does not assume the container id is started with `docker://`, but it does check the container id, and report an error if the id is not started with `docker://`, because other runtimes have not been supported.

> assumes that it can create the debug container using a docker client the end point unix:///var/run/docker.sock. ( In my case nothing is listening on that socket )

Actually, the docker endpoint is configurable:

https://github.com/aylei/kubectl-debug/blob/1fd0bac15750d42c82b70376204d04142ca3583f/pkg/agent/config.go#L21

**Comment by dee0** [comment]
Thanks for confirming that docker is required.    I don't own the kubernetes deployment so I cannot change it to use a different runtime.  ( Oh, and docker isn't even installed in these environments )

From what I have seen in the code so far, it looks like adding support for the containerd runtime wouldn't be too hard.   Do you agree?

**Comment by dee0** [comment]
Fwiw I have containerd support pretty much working.   I expect I'll open a pull request within a couple of days.
